sharingBookReview-SERVICE/sharingBookReview-BE

routes/book.js, routes/books.js, routes/index.js
=> 추가> routes/books.js 

routes/books.js
=> modify_books

models/index.js
Import and export all models through /models/index.js
=> db indexing

models/review.js, routes/reviews.js
Use pre deleteOne middleware to implement ON DELETE CASCADE
=> Refactor reviews router delete method

models/comment.js, models/review.js, routes/feeds.js, routes/reviews.js
프론트분들의 건의로 인해 모델에 종속된 아이디값들 이름을 바꾸었습니다 논의필요하시면 comment 달아주시면 감사하겠습니다.
=> change name of id

models/review.js, routes/feeds.js
=> Update feeds router

controllers/index_tags.js, package.json
2단계 : 프론트에서 정해주는 갯수만큼 topTags 에 넣어서 책 다큐먼트에 저장
3단계 : 프론트로 결과값 주기
=> Tag 추출 1단계 완료

controllers/index_tags.js, models/book.js
과정 설명
1. scheduleJob : 초가 0이 될 때마다 콜백 실행 (즉, 1분마다)
2. 지난 1분간 변경된 책들의 목록의 집합을 구함
3. 목록에 들어간 책들을 ChangeIndexed 테이블에서 삭제
4. 목록을 통해서 해당하는 책들을 불러옴
5. 각 책마다 순회하면서
6. 책의 모든 리뷰의 모든 태그를 담은 배열을 구함
7. 배열로부터 집합을 구함
8. 집합을 순회하면서 각 요소의 등장 빈도를 계산
9. 내림차순으로 정렬함
10. 10등까지 끊고
11. 빈도를 버리고 이름만으로 이루어진 배열 구함
12. 배열을 책의 topTags 속성에 넣고 저장
=> Finish topTags

routes/comments.js, routes/reviews.js
1. Response에 필요하다면 객체가 반환되게 함
2. 전반적으로 에러 처리 부분을 향상
=> Update responses and errors

models/review.js, routes/books.js, routes/reviews.js
=> Like 2차 시도

exp_list.js, models/comment.js, models/review.js, models/user.js, routes/comments.js, routes/reviews.js
좋아요 한개당 0.1
글을 작성했을 때 3
댓글을 최초로 적었을 때 1
완료
컬렉션을 만들었을 때 3
팔로우를 1인당 받았을 때 2 취소 시 점수 뺏기
는 컬렉션과 팔로우 완료되고 업데이트
=> levelup like review and firstcomment

routes/feeds.js
바디에 담기는 리뷰 아이디값 이후의 10개를 보내줍니다.
=> Update feeds to scroll 10

models/collection.js, routes/collections.js
=> Collection 2차

models/suggestion.js, routes/suggestion.js
=> Refactor suggestion

models/book.js, models/collection.js, models/review.js
컬렉션 스키마를 비롯한 여러 스키마에 걸쳐서 isbn 에 13자리 숫자만 입력할 수 있도록 고쳤습니다. 사용자가 임의로 문자열이나 다른걸 넣어서 populate가 잘 작동하지 않은 오류가 있었네요.
=> Fix collection schema

models/book.js, models/collection.js, models/review.js
Reverts sharingBookReview-SERVICE/sharingBookReview-BE#103
=> Revert "Fix collection schema"

routes/users.js
1. 기존의 안되던 코드 해결
2. 리뷰만 보여주던 것에서 컬렉션도 같이 보내줌
=> Update user feeds

controllers/utilities.js, models/collection.js, routes/collections.js, routes/comments.js
경험치 파트를 제외한 컬렉션의 댓글을 완성했습니다.
또한 기존 커멘트 라우터를 손봤습니다.
=> Implement Collection comment

models/follow.js, routes/follow.js, routes/users.js
1. 내 피드 follow list vs 다른 유저 피드 follow list 차별화
2. following 여부를 알 수 있는 static 함수 추가
- 인자로 instance 를 받기 때문에 feed 에서 processlikesinfo와 혼용하여 쓸수 없는점 refactoring 필요
=> different users followlist

models/book.js, models/changes_index.js, models/collection.js, models/comment.js, models/follow.js, models/review.js, models/suggestion.js, models/user.js
스키마들을 좀더 다듬어서 통일감 있고
줄 바꿈이 너무 많던걸 코드 내용을 줄이는 등의 방법으로 가독성을 높여봤습니다.
=> Refactor schemas

routes/users.js
=> delete follow cascading

models/user.js, routes/feeds.js
클라이언트에서 리뷰를 읽고 해당 api 를 호출하면 db에 적용합니다.
=> Add read_review routes
